id: joshuadeguzman/ButtonsKt
name: ButtonsKt
url: https://jmdg.io/ButtonsKt/
license: MIT License
licenseUrl: https://opensource.org/licenses/MIT
favicon: png
download:
  popup: false
  url: https://github.com/joshuadeguzman/ButtonsKt/releases

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/joshuadeguzman/ButtonsKt
  - title: Joshua de Guzman
    url: https://bit.ly/joshuadeguzman

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/joshuadeguzman/ButtonsKt
  - title: Issues
    url: https://github.com/joshuadeguzman/ButtonsKt/issues?state=open

# header
header:
  color1: "#1abc9c"
  color2: "#2c3e50"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: joshuadeguzman
  repo: ButtonsKt

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
